
image: Visual Studio 2015
#image: Visual Studio 2017

environment:
  matrix:
  - MSYSTEM: MINGW64

install:
  - choco install dependencywalker -y --allow-empty-checksums

build_script:
  - C:\msys64\usr\bin\pacman -Syuu --noconfirm
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/.appveyor_build.sh"

artifacts:
  - path: knossos.win64.zip

deploy:
  #release: myproduct-v$(appveyor_build_version)
  release: v5.0-emdrp
  description: 'v5.0-emdrp'
  provider: GitHub
  auth_token:
    secure: w74a0EqE8olcyKcn3NFusPQ39qvUIlwZdXKxoXHX46jCDKxQdoEkT0DKoO3sMD8H
  artifact: knossos.win64.zip
  draft: false
  prerelease: false
  on:
    branch: emdrp
    appveyor_repo_tag: true        # deploy on tag push only

